# X-UI Exporter Configuration Example
# This file contains all the configuration options available for the X-UI Exporter
# Command-line flags will override these settings if provided

# X-UI panel connection details
# Base URL of the X-UI panel (required)
panel-base-url: "https://your-panel-url"

# Username for X-UI API authentication (required)
panel-username: "your-username"

# Password for X-UI API authentication (required)
panel-password: "your-password"

# Skip SSL certificate verification (NOT recommended for production)
# Use this only if your panel uses self-signed certificates
# or when using a private trusted network
insecure-skip-verify: false

# General settings
# Interval in seconds between updates from the panel (default: 30)
update-interval: 30

# Timezone for time-based operations (default: UTC)
timezone: "UTC"

# Metrics server configuration
# Bind address for the metrics server (default: 0.0.0.0)
metrics-ip: "0.0.0.0"

# Port for the metrics server (default: 9090)
metrics-port: "9090"

# Clients metrics bytes (0 = all data, else top N rows)
# Limit rows for clients up/down bytes
clients-bytes-rows: 0

# Enable authentication for metrics endpoint
metrics-protected: false

# Username for metrics authentication (required if metrics-protected is true)
metrics-username: "metricsUser"

# Password for metrics authentication (required if metrics-protected is true)
metrics-password: "MetricsVeryHardPassword"
